### ISSUE TITLE
The dropdown menu does not disappear when clicked.

### ISSUE THREAD

**Issue by flads** [Landish/pingcrm-react#27]
![Screenshot from 2021-01-31 16-29-47](https://user-images.githubusercontent.com/43182319/106395599-d2c74c00-63e1-11eb-8bd4-85c0274d7fdb.png)

**Comment by Landish** [comment]
@flads can you send PR?

**Comment by flads** [comment]
I don't work with React, I just found the bug. If you want to leave it here for someone contribute to the solution, feel free. Otherwise, you can close this issue.

**Comment by Landish** [comment]
Closed. See: #28
