### ISSUE TITLE
CORS issues with BrowserSync

### ISSUE THREAD

**Issue by alechko** [Landish/pingcrm-react#38]
I'm using DDEV as my Docker backend env and when launching the project with [BrowserSync](https://laravel-mix.com/docs/6.0/browsersync), the project get loaded from `localhost:3000` or similar.

The main pages load with no issue, but any XHR action (for example pagination) performed from the page throwing the following CORS errors:

` Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://pingcrm-react.ddev.site/organizations?page=2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://projectddev.site/organizations?page=2. (Reason: CORS request did not succeed).`

Sometimes the first XHR request works, but never the second or the following ones.

Is there anything I can do to make it work?

![image](https://user-images.githubusercontent.com/1391846/125503319-94c70a84-20ca-4dd1-a3f4-5e3f654edfce.png)

**Comment by Landish** [comment]
@alechko 

This repository has been updated to Laravel 11. Instead of Laravel mix now it uses Vite. 

Please update it in order to see if the issue still exists. 

Closing this one for now.
