### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by Wiz-Amit** [Landish/pingcrm-react#42]
Please update dependencies to support PHP 8

**Comment by renhyl** [comment]
For anyone interested:
Dockerized project for PHP 8.2 + MariaDb 10 for Laravel 10 + InertiaJS with Ping CRM
https://github.com/renhyl/docker-php-8.2-laravel-10-inertiajs-ping-crm

**Comment by Landish** [comment]
Resolved in #64
