### ISSUE TITLE
Laravel 10 Upgrade

### ISSUE THREAD

**Issue by artemio87** [Landish/pingcrm-react#66]
How we move to Laravel 10 ?

**Comment by renhyl** [comment]
For anyone interested:
Dockerized project for PHP 8.2 + MariaDb 10 for Laravel 10 + InertiaJS with Ping CRM
https://github.com/renhyl/docker-php-8.2-laravel-10-inertiajs-ping-crm

**Comment by Landish** [comment]
It has been updated to Version 11. 
Frontend now uses Vite instead of Laravel Mix.
Typescript version coming soon.

See: #72
