### ISSUE TITLE
Upgradation of laravel and inertia js

### ISSUE THREAD

**Issue by Shivam-netweb** [Landish/pingcrm-react#69]
Please update the version of laravel and interia js with the latest one so that the users can easily clone and understand the things from the example

**Comment by fouteox** [comment]
Hello : https://github.com/fouteox/pingcrm-react-inertia-laravel

**Comment by renhyl** [comment]
For anyone interested:
Dockerized project for PHP 8.2 + MariaDb 10 for Laravel 10 + InertiaJS with Ping CRM
https://github.com/renhyl/docker-php-8.2-laravel-10-inertiajs-ping-crm

**Comment by desarrollowebvnzla** [comment]
Hello, when will the repository with the new version be ready?

**Comment by Landish** [comment]
It has been updated to Version 11. 
Frontend now uses Vite instead of Laravel Mix.
Typescript version coming soon.

See: #72
