### ISSUE TITLE
Can we get pingcrm-react-ts version?

### ISSUE THREAD

**Issue by anburocky3** [Landish/pingcrm-react#71]

**Comment by SavioNicodemos** [comment]
If you want some help, I can help in implement this.

**Comment by anburocky3** [comment]
It would be great if we have that functionality, will create a repository soon.

**Comment by Landish** [comment]
Hi @anburocky3 @SavioNicodemos 

Thanks for showing the interest. 

There is a current PR open about transforming to Typescript. #73 Please check it out. 

I started few days ago and currently it's in a WIP state.

**Comment by SavioNicodemos** [comment]
Oh great! I will have a look and see the PR. Thank you!

**Comment by anburocky3** [comment]
Update: I hope it has been merged. So closing this issue.
